apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: itachi-pod-ds # daemonset的名字
spec:
  selector:
    matchLabels:
      app: itachi-pod-ds-label # 选择器匹配的标签
  template:
    metadata:
      labels:
        app: itachi-pod-ds-label # 标签
    spec:
      containers:
      - name: container-1-itachi # 容器的名字, 一个pod内可以有多个容器
        image: vitachi/up_flask # 容器的镜像
        ports:
        - containerPort: 10080 # 只是一个信息, 类似于Dockerfile的EXPOSE
