stages:
  - docker_build_flask
  - docker_build_nginx
  - docker_build_mysql
  - docker-compose_up

default:
  before_script:
    - sudo docker version
    - sudo docker-compose --version

docker_build_flask:
  stage: docker_build_flask
  script:
    - cd flask
    - sudo docker build -t harbor.itachi.tech/itachi_web/itachi_flask .
    - sudo docker push harbor.itachi.tech/itachi_web/itachi_flask
  only:
    - master
  tags:
    - build

docker_build_nginx:
  stage: docker_build_nginx
  script:
    - cd nginx
    - sudo docker build -t harbor.itachi.tech/itachi_web/itachi_nginx .
    - sudo docker push harbor.itachi.tech/itachi_web/itachi_nginx
  only:
    - master
  tags:
    - build

docker_build_mysql:
  stage: docker_build_mysql
  script:
    - cd mysql
    - sudo docker build -t harbor.itachi.tech/itachi_web/itachi_mysql .
    - sudo docker push harbor.itachi.tech/itachi_web/itachi_mysql
  only:
    - master
  tags:
    - build

docker-compose_up:
  stage: docker-compose_up
  script:
    - sudo docker-compose pull
    - sudo docker-compose up -d
#    - sudo docker stack deploy itachi -c docker-compose.yml --resolve-image "always" --with-registry-auth
#      -resolve-image "always"：总是使用最新镜像
#      --with-registry-auth：	传递授权，只需此台宿主机有访问镜像仓库的授权，其它宿主机也可获得授权
  only:
    - master
  tags:
    - compose